sudo: required
services:
 - docker

before_install:
 - docker build -t ratika31/docker-newreact -f Dockerfile.dev .

script:
 - docker run -e CI=true ratika31/docker-newreact npm run test -- --coverage

deploy: 
 provider: elasticbeanstalk
 region: "eu-west-2"
 app: "docker-react"
 env: "DockerReact-env"
 bucket_name: "elasticbeanstalk-eu-west-2-217456606433"
 bucket_path: "docker-react"
 skip_cleanup: true
 on:
  branch: master
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key:
  secure: "$AWS_SECRET_KEY"
