sudo: required
services:
 - docker

before_install:
 - docker build -t ratika31/docker-newreact -f Dockerfile.dev .

script:
 - docker run -e CI=true ratika31/docker-newreact npm run test -- --coverage
